name: XMAS
main: de.minestar.xmas.XMASCore
version: ${pom.version}
depend: [MineStarLibrary]
commands:
    xmas:
        description: XMAS related commands.
        usage: /<command> <cmd 1> ... <cmd n>